# Generated by Django 2.2.10 on 2021-05-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='answers',
            field=models.ManyToManyField(blank=True, null=True, to='api_app.AnswerModel'),
        ),
    ]
