# Generated by Django 2.2.10 on 2021-05-05 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_app', '0004_auto_20210505_0537'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text_answer', models.CharField(max_length=1000, null=True)),
                ('answers', models.ManyToManyField(null=True, to='api_app.AnswerModel')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.PollModel')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.QuestionModel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
