# Generated by Django 2.2.10 on 2021-05-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_useranswermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='answers',
            field=models.ManyToManyField(blank=True, help_text='Только для вопросов с выбором варианта!', to='api_app.AnswerModel'),
        ),
        migrations.AlterField(
            model_name='useranswermodel',
            name='answers',
            field=models.ManyToManyField(to='api_app.AnswerModel'),
        ),
    ]
